name: Pipeline CI

on:
  push:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: '30 2 * * *'

jobs:
  testes:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes
        run: npm run test:report

      - name: Publicar relatório
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: relatorio-testes
          path: reports/
          retention-days: 30